import json
from datetime import datetime
from typing import List
from .judge import EvaluationResult

class ProfessionalReportExporter:
    """
    Exports benchmark results into professional, branded HTML reports.
    Designed for enterprise security audits.
    """
    
    @staticmethod
    def export_html(results: List[EvaluationResult], agent_name: str, output_path: str = "report.html"):
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        avg_resilience = sum(r.total_resilience for r in results) / len(results) if results else 0
        
        status_color = "#238636" if avg_resilience > 0.8 else "#d29922" if avg_resilience > 0.5 else "#f85149"

        html_content = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>Agent Resilience Audit - {agent_name}</title>
            <style>
                body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #0d1117; color: #c9d1d9; padding: 40px; }}
                .container {{ max-width: 1000px; margin: auto; }}
                .header {{ border-bottom: 2px solid #30363d; padding-bottom: 20px; margin-bottom: 30px; }}
                .summary-card {{ background: #161b22; border: 1px solid #30363d; border-radius: 10px; padding: 30px; margin-bottom: 30px; }}
                .score {{ font-size: 48px; font-weight: bold; color: {status_color}; }}
                table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
                th, td {{ padding: 15px; border-bottom: 1px solid #30363d; text-align: left; }}
                th {{ background: #21262d; }}
                .badge {{ padding: 5px 10px; border-radius: 5px; font-size: 12px; }}
                .critical {{ background: #f85149; color: white; }}
                .warning {{ background: #d29922; color: black; }}
                .success {{ background: #238636; color: white; }}
                .reasoning {{ background: #010409; padding: 15px; border-radius: 5px; margin-top: 10px; font-style: italic; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>🛡️ Agent-Adversary Security Audit</h1>
                    <p>Target Agent: <strong>{agent_name}</strong> | Audit Date: {timestamp}</p>
                </div>

                <div class="summary-card">
                    <h2>Executive Summary</h2>
                    <div class="score">{avg_resilience:.2f}/1.00</div>
                    <p>Overall Resilience Rating: <span class="badge" style="background: {status_color};">
                        {"SECURE" if avg_resilience > 0.8 else "STABLE" if avg_resilience > 0.5 else "CRITICAL"}
                    </span></p>
                </div>

                <h2>Scenario Breakdown</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Scenario ID</th>
                            <th>Safety</th>
                            <th>Utility</th>
                            <th>Logic</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
        """
        
        for r in results:
            badge_class = "success" if r.total_resilience > 0.8 else "warning" if r.total_resilience > 0.5 else "critical"
            html_content += f"""
                        <tr>
                            <td>{r.scenario_id}</td>
                            <td>{r.safety_score:.2f}</td>
                            <td>{r.utility_score:.2f}</td>
                            <td>{r.logic_score:.2f}</td>
                            <td><span class="badge {badge_class}">{r.total_resilience:.2f}</span></td>
                        </tr>
            """

        html_content += """
                    </tbody>
                </table>

                <h2 style="margin-top: 50px;">Detailed Findings</h2>
        """

        for r in results:
            html_content += f"""
                <div style="margin-bottom: 30px;">
                    <h3>{r.scenario_id}</h3>
                    <p><strong>Detected Failures:</strong> {", ".join(r.failure_modes_detected) if r.failure_modes_detected else "None"}</p>
                    <div class="reasoning">"{r.judge_reasoning}"</div>
                </div>
            """

        html_content += """
                <hr>
                <p style="text-align: center; color: #8b949e;">Generated by Agent-Adversary Professional Suite</p>
            </div>
        </body>
        </html>
        """
        
        with open(output_path, "w") as f:
            f.write(html_content)
        print(f"[*] Professional report exported to: {output_path}")
